v2ray_base64_url: 'https://raw.githubusercontent.com/hkpc/V2ray-Configs/main/All_Configs_base64_Sub.txt'
clash_base64_url: 'https://raw.githubusercontent.com/hkpc/Autoproxy/main/Long_term_subscription_num'
