name: Collect

on:
  workflow_dispatch:
  push:
    paths:
      - "./EternityBase"
      - "./sub/sub_merge_base64.txt"
      - "./sub/sub_merge_yaml.yml"
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  main:
    name: Collect & SpeedTest & Filter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./utils/localserver
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Install Requirements
        run: pip install -r ./utils/requirements.txt

      - name: Running Collector
        run: |
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          node ./utils/localserver/index.js &
          sleep 2
          python ./utils/list_merge.py

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add ./sub ./utils/Country.mmdb README.md
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main

      - name: Run Lite Speedtest
        run: |
          sleep 5
          sudo sh ./utils/speedtest2_yaml.sh
          python ./utils/output.py

      - name: Commit Speedtest Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add EternityBase Eternity Eternity.txt ./sub/sub_merge.txt ./sub/sub_merge_base64.txt LogInfo.txt ./sub/splitted/*
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Tested"

      - name: Push Speedtest Results
        uses: ad-m/github-push-action@master
        with:
          branch: main

      - name: Run Converter & Formatter
        run: |
          sleep 5
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          python ./utils/eternity_convert.py

      - name: Commit Converted Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add Eternity.yml Eternity README.md ./update/* LogInfo.txt
          git clean -f -d
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Filtered"

      - name: Push Converted Results
        uses: ad-m/github-push-action@master
        with:
          branch: main
